apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-webhook
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "chart.name" . }}.webhook.po
    rules:
      - resources: ["pods"]
        apiGroups: [""]
        apiVersions: ["v1"]
        {{- toYaml .Values.validationAdmissionController.rule | nindent 8 }}
    clientConfig:
      service:
        name: admit-tag-image-webhook-service
        namespace: admit-tag-image-webhook
        path: /pods
      caBundle: {{ .Values.certs.ca | toString | b64enc }}
    {{- toYaml .Values.validationAdmissionController.common | nindent 4 }}
  - name: {{ include "chart.name" . }}.webhook.deploy
    rules:
      - resources: ["podtemplates"]
        apiGroups: [""]
        apiVersions: ["v1"]
        {{- toYaml .Values.validationAdmissionController.rule | nindent 8 }}
    clientConfig:
      service:
        name: admit-tag-image-webhook-service
        namespace: admit-tag-image-webhook
        path: /podtemplates
      caBundle: {{ .Values.certs.ca | toString | b64enc }}
    {{- toYaml .Values.validationAdmissionController.common | nindent 4 }}