version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Rome'
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001"
      DNSSEC: true
      ServerIP: #Host server IP
      ADMIN_EMAIL: # Admin email
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local.dualab.duckdns.org`)"
      - "traefik.http.routers.pihole.service=pihole@docker"
      - "traefik.http.routers.pihole.middlewares=pihole-admin-prefix@docker"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=letduckdns"
      - "traefik.http.routers.pihole.tls.domains[0].main=local.dualab.duckdns.org"
      - "traefik.http.routers.pihole.tls.domains[0].sans=*.local.dualab.duckdns.org"
      - "traefik.http.services.pihole.loadbalancer.server.port=8080"
      - "traefik.tcp.routers.pihole.middlewares=pihole-vpn-tunnel-ips@docker"
      - "traefik.tcp.middlewares.pihole-vpn-tunnel-ips.ipwhitelist.sourcerange=10.8.0.0/24"
      - "traefik.http.middlewares.pihole-admin-prefix.addprefix.prefix=/admin"

