apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-secret
  namespace: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.certs }}
  cert_file: {{ .public | toString | b64enc }}
  cert_key: {{ .private | toString | b64enc }}
  {{- end }}