apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "duckdns-k8s.fullname" . }}-policy
  namespace: {{ include "duckdns-k8s.name" . }}
  labels:
    {{- include "duckdns-k8s.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "duckdns-k8s.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress